@echo off
cls
echo Win 1251 codepage
echo ╚ёяюы№чєщЄх ¤ЄюЄ Їрщы Єюы№ъю Єюуфр ъюуфр юс√ўэ√ь ёяюёюсюь яЁюуЁрььє 
echo эх єфр╕Єё  чряєёЄшЄ№.
echo ╧хЁт√щ ярЁрьхЄЁ [╚ь  яЁюуЁрьь√ яюышэюьшры№э√щ °шЇЁ]
echo ┬ЄюЁющ ярЁрьхЄЁ [╩рЄрыюу уфх эрїюф Є№ё  Їрщы√ Alphabet.dat,Teor.txt,Product.gf]
echo ═ряЁшьхЁ :
echo d:\zikk\cycle\cycle.exe d:\zikk\cycle\
echo --------------------------------------------------------------------------------
echo DOS 866 codepage
echo Используйте этот файл только тогда когда обычным способом программу 
echo не удаётся запустить.
echo Первый параметр [Имя программы полиномиальный шифр]
echo Второй параметр [Каталог где находяться файлы Alphabet.dat,Teor.txt,Product.gf]
echo Например :
echo d:\zikk\cycle\cycle.exe d:\zikk\cycle\
echo --------------------------------------------------------------------------------

echo on
d:\zikk\cycle\cycle.exe d:\zikk\cycle\